#!/bin/bash
# Script for dual monitors on openbox

LVDS="LVDS1"
VGA="VGA1"
HDMI="HDMI1"

CHK_VGA=$(xrandr |grep $VGA | awk ' { print $2 } ')
CHK_HDMI=$(xrandr |grep $HDMI | awk ' { print $2 } ')

CHK_VGA_G=$(xrandr |grep $VGA | grep "+")
CHK_HDMI_G=$(xrandr |grep $HDMI | grep "+")

function hdmi_only(){
#xrandr --output LVDS1 --mode 1366x768 --pos 0x312 --rotate normal --output HDMI1  --right-of LVDS1 --rotate normal
xrandr --output LVDS1 --off --output HDMI1 --rotate normal
}

if [ "$CHK_HDMI" == "connected" ]; then
    hdmi_only

elif [ "$CHK_HDMI_G" ]; then
    hdmi_only
else
    xrandr --output $LVDS --auto

fi

#nitrogen --restore
/bin/sh ~/.fehbg

exit 0
