#!/bin/bash
# Script for dual monitors on openbox

LVDS="LVDS1"
VGA="VGA1"
HDMI="HDMI1"

CHK_VGA=$(xrandr |grep $VGA | awk ' { print $2 } ')
CHK_HDMI=$(xrandr |grep $HDMI | awk ' { print $2 } ')

CHK_VGA_G=$(xrandr |grep $VGA | grep "+")
CHK_HDMI_G=$(xrandr |grep $HDMI | grep "+")

function hdmi_only(){
xrandr --output LVDS1 --mode 1366x768 --pos 0x0 --rotate normal --output HDMI1 --auto --pos 1366x0 --rotate normal

}

if [ "$CHK_HDMI" == "connected" ]; then
    hdmi_only

elif [ "$CHK_HDMI_G" ]; then
    hdmi_only
else
    xrandr --output $LVDS --auto

fi

/usr/bin/bash /home/leo/.fehbg
/usr/bin/bash /home/leo/.conky/quickConky


exit 0
