#!/bin/bash
# Script for dual monitors on openbox

LVDS="LVDS1"
VGA="VGA1"
HDMI="HDMI1"

CHK_VGA=$(xrandr |grep $VGA | awk ' { print $2 } ')
CHK_HDMI=$(xrandr |grep $HDMI | awk ' { print $2 } ')

CHK_VGA_G=$(xrandr |grep $VGA | grep "+")
CHK_HDMI_G=$(xrandr |grep $HDMI | grep "+")

function double_screen(){
	source ~/.screenlayout/double1920p.sh
}

if [[ "$CHK_HDMI" == "connected" && "$CHK_VGA" == "connected" ]]; then 
	double_screen
else
    xrandr --output $LVDS --auto

fi

#nitrogen --restore
/bin/sh ~/.fehbg

exit 0
