#!/bin/bash


## Options taken (for case)
# up, down, toggle


# Configuration
STEP="5"    # Anything you like.
UNIT="%"   # dB, %, etc.

# Set volume
SETVOL="/usr/bin/pamixer"
GETVOL=$(/usr/bin/pamixer --get-volume | cut -c -3)
case "$1" in
    "up")
	if [ "$GETVOL" -le "95" ]; then
        $SETVOL "--increase" $STEP
	fi
        ;;
  "down")
	if [ $GETVOL -ge 0 ]; then
        $SETVOL "--decrease" $STEP
	fi
        ;;
  "toggle")
          $SETVOL "--toggle-mute"
          ;;
esac

# Get current volume and state
#VOLUME=$(pamixer get Master | grep 'Mono:' | cut -d ' ' -f 6 | sed -e 's/[^0-9]//g')
STATE=$(pamixer --get-mute)

# Show volume with volnoti
if [[ $STATE = "true" ]]; then
  volnoti-show -m
else
  volnoti-show $GETVOL
fi

exit 0
