#!/bin/bash

# This script has two dependencies:
# pamixer (which on Arch Linux is available from the AUR)
# volnoti (also available from the AUR)
#
# All is does it read info from pamixer and process it to
# change sound volume or mute status and display a pretty notification.
#
# It takes two arguments, the first one determines which sink (device)
# you want to use and the second argument determines the action.
# First argument should be an integer and the second has to be either up, down or toggle.


# Configuration
STEP="5"   # Any number you like.
UNIT="%"   # dB, %, etc.


# Set volume binary to be executed
SETVOL="/usr/bin/pamixer -s $1"
# Get the volume status for the notification
GETVOL=$(/usr/bin/pamixer -s $1 --get-volume | cut -c -3)

# Determines what action will be taken
case "$2" in
    "up")
        if [ "$GETVOL" -le "95" ]; then
            $SETVOL "--increase" $STEP
        fi
        ;;
    "down")
        if [ $GETVOL -ge 0 ]; then
            $SETVOL "--decrease" $STEP
        fi
        ;;
    "toggle")
        $SETVOL "--toggle-mute"
        ;;
esac

# Get current mute state
STATE=$(pamixer -s $1 --get-mute)

# Show volume with volnoti
if [[ $STATE = "true" ]]; then
    volnoti-show -m
else
    volnoti-show $GETVOL
fi

exit 0
